version: '3'
services:
  dedi-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    volumes:
      - $PWD/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dedi-service

  dedi-adminer:
    image: adminer
    container_name: "${APP_NAME}_ADMINER"
    ports:
      - '8081:8080'
    networks:
      - dedi-service

  dedi-redis:
    image: "redis:alpine"
    container_name: "${APP_NAME}_REDIS"
    networks:
      - dedi-service
    volumes:
     - $PWD/redis:/var/lib/redis

  dedi-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/app
    container_name: "${APP_NAME}_APP"
    image: app-dedi-service-dev
    env_file:
      - .env
    environment:
      DB_HOST: dedi-mysql
      REDIS_HOST: dedi-redis
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - dedi-mysql
      - dedi-redis
    networks:
      - dedi-service

networks:
  dedi-service: