version: '3'
services:
  dedi-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    volumes:
      - $PWD/mysql:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dedi-network

  dedi-mongo:
    image: mongo
    container_name: "${APP_NAME}_MONGO"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${LOG_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${LOG_MONGO_PASSWORD}
    volumes:
      - $PWD/mongodb:/data/db
    restart: 'always'
    networks:
      - dedi-network

  dedi-redis:
    image: "redis:alpine"
    container_name: "${APP_NAME}_REDIS"
    restart: always
    networks:
      - dedi-network
    volumes:
     - $PWD/redis:/var/lib/redis

  dedi-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    image: app-dedi-service
    env_file:
      - .env
    environment:
      DB_HOST: dedi-mysql
      REDIS_HOST: dedi-redis
    links:
      - mongo
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - dedi-mysql
      - dedi-redis
      - dedi-mongo
    networks:
      - dedi-network

networks:
  dedi-network: