version: '3'
services:
  dedi-mysql:
    image: mysql
    container_name: "${APP_NAME}_MYSQL"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - $PWD/mysql:/var/lib/mysql
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dedi-network

  dedi-redis:
    image: "redis:alpine"
    container_name: "${APP_NAME}_REDIS"
    restart: always
    networks:
      - dedi-network
    volumes:
     - $PWD/redis:/var/lib/redis

  dedi-app:
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    image: boilerplate-dedi-service
    env_file:
      - .env
    environment:
      DB_HOST: dedi-mysql
      REDIS_HOST: dedi-redis
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - dedi-mysql
      - dedi-redis
    networks:
      - dedi-network

networks:
  dedi-network: